baseurl = "/"
languageCode = "en-us"
title = "万水千山"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home·主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Resume·简历"
    url = "/resume/"
    weight = 2
[[menu.main]]
    name = "Slide·展示"
    url = "/slide/"
    weight = 3
[[menu.main]]
    name = "Application·应用"
    url = "/application/"
    weight = 4
[[menu.main]]
    name = "Fiction·小说"
    url = "/ebook/"
    weight = 5
[[menu.main]]
    name = "Blog·博客"
    url = "/blog/"
    weight = 6
[[menu.main]]
    name = "Academics·学术"
    url = "/academics/"
    weight = 7
[[menu.main]]
    name = "Categories·类别"
    url = "/categories/"
    weight = 8
[[menu.main]]
    name = "Tags·标签"
    url = "/tags/"
    weight = 9
[[menu.main]]
    name = "About·关于"
    url = "/about/"
    weight = 10

[params]
    description = "Across Mountains and Seas"
    footer = "&copy; 2019-2022 [京ICP备2021008534号-1](https://beian.miit.gov.cn/)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true