---
title: "赵柯论文四篇：德国与欧洲"
author: "赵柯"
date: '2019-06-30'
slug: 赵柯论文四篇-德国与欧洲
tags:
- 德国
- 欧洲
categories: International Relation
---

赵柯, 中共中央党校国际战略研究院副教授


## 信任的代价

```
@article{
  赵柯-630,
  Author = {赵柯},
  Title = {信任的代价},
  Journal = {中国投资},
  Number = {23},
  Pages = {22-23},
  Note = {页数: 2},
  Abstract = {},
  Keywords = {},
  Year = {2018}
}
```

- 1949年，苏联原子弹爆炸成功，美国无法单方面对苏联进行核讹诈。1950年，朝鲜战争爆发，苏东阵营在东亚采取攻势。
- 美国感到巨大压力，决定重新武装德国，利用德国的资源抵御苏联可能的进攻。
- 对此，法国极度惊恐。1950年，法国提出煤钢联营，使德国无法秘密进行战争准备。

&nbsp;

- 1990年，德国统一，改变了整个欧洲的安全格局。以法国为首的欧洲国家向德国施压，要求德国放弃已是全球第二大储备货币的马克，共同创建欧元。
- 1991年，《欧洲联盟条约》（马约）签署，马克消失，德国将主权货币置于欧洲共同监管之下，便在很大程度上剥夺了德国发动战争的能力。
- 欧元的创建并非出于单纯的经济考量，而更是出于战略考量。因为主权货币和煤钢一样，都是可以用来发动战争的战略物资。
- 法国事与愿违：欧元成倍地放大了德国的工业竞争力，使德国权倾欧洲，成为欧洲一体化唯一可能的领导者。


## “后默克尔”时代德国向何处去?

```
@article{
赵柯李刚-629,
   Author = {赵柯 and 李刚},
   Title = {“后默克尔”时代德国向何处去?},
   Journal = {当代世界},
   Number = {01},
   Pages = {33-38},
   Note = {页数: 6},
   Abstract = {随着德国总理默克尔卸任基督教民主联盟党主席,她将逐步淡出德国的权力中心,但其留下的政治"遗产"更多地会被继承和修正,而非被颠覆性的抛弃。"后默克尔"时代的德国在内政方面将会重点聚焦于重建"共识政治",维护社会公正,发展"数字经济";外交领域的优先议题是继续推动欧元区的改革,确保欧元区经济金融的稳定。美国仍是德国在欧盟之外最重要的伙伴,跨大西洋战略同盟关系会进一步稳固。},
   Keywords = {“后默克尔”时代;共识政治;数字经济;跨大西洋战略同盟关系;欧元区},
   Year = {2019} }
```

议题|德国内部对默克尔的不满和批评|未来趋势
--|--|--
内政|无力维系“共识政治”，没有及时意识到右翼民粹政党的崛起对主流政治的巨大威胁|重建“共识政治”
内政|没有回应2008年后时代潮流和大众心理的呼唤，对平等的重视不足，使基民盟在选举中遭遇惨败|增加对社会平等的关注
内政|产业结构老化，支柱仍是汽车、化工、机械、电气，在新兴产业中落后|加快发展数字经济，尤其希望在标准领域大有作为
外交|对欧元区改革和财政一体化态度消极、浪费时机|唯有加速欧洲一体化，才有助于德国根本利益的实现
外交||德国暂时离不开美国，对美国仍然深度依赖


## 资本主义制度再平衡:全民基本收入的理念与实践

```
@article{
赵柯李刚-631,
   Author = {赵柯 and 李刚},
   Title = {资本主义制度再平衡:全民基本收入的理念与实践},
   Journal = {欧洲研究},
   Volume = {37},
   Number = {01},
   Pages = {1-21+156},
   Note = {页数: 22},
   Abstract = {近年来,全民基本收入已成为西方学界和政界的一股新的政策理念思潮。本文对全民基本收入思想的起源与发展、制度实践和影响进行了分析,认为当前全民基本收入从学术理念到成为政策选择,是西方资本主义国家面对经济全球化带来的不平等加剧、民粹势力兴起,以及科技革命即将带来的大量失业的前景下进行的一次制度"再平衡",试图缓和市场经济与民主政治之间、经济效率与社会公平之间的内在张力。全民基本收入制度也面临高昂财政负担、道德风险等问题,一些国家已经通过制度试验对其进行改进。在此过程中,全民基本收入也产生了多样化的过渡性制度形态,这在一定程度上预示着西方资本主义制度自我修复和变革的新方向。},
   Keywords = {全民基本收入;不平等;效率;经济增长;资本主义制度},
   Year = {2019} }
```

- 性质：对里根-撒切尔革命的反革命。

- 背景：（1）不平等加剧（不仅是美国，欧洲国家也一样，即使没有美国那么严重），民粹主义兴起，社会凝聚力减弱；（2）未来，人工智能和自动化会淘汰大量的工作岗位，提高劳动力市场的准入门槛，社会矛盾不可避免地会加剧。

- 解决方案：无偿发放的全民基本收入，作为社会保护网的一种新形式，为失业人群兜底，降低不平等程度。

- 短期目的：降低不平等在一定程度上有利于经济增长。因为不平等会导致 A) 削弱人力资本的积累；B) 减少投资，因为低收入者无法获得融资；C) 影响宏观经济的稳定性——投资意愿下降和债务消费增加。

- 中长期目的：防止社会矛盾激化导致的动荡。


## 德国主导欧洲经济:能力还是运气?

```
@article{
赵柯-549,
   Author = {赵柯},
   Title = {德国主导欧洲经济:能力还是运气?},
   Journal = {中国投资},
   Number = {09},
   Pages = {23-25},
   Note = {页数: 3},
   Abstract = {},
   Keywords = {},
   Year = {2018} }
```

### 德国掌控了欧洲的贸易网络和资本网络

贸易：德国是欧洲资源的整合者，是欧盟贸易网络的中心。^[从贸易结构上看，德国从欧盟其他国家进口的多是工业原材料和中间产品，而出口的主要是工业制成品。也就是说，来自欧盟其他国家的出口经过德国的再加工，一部分重新回到欧盟国家，另一部出口到世界其他国家。]

资本：德国通过强大的工业竞争力以贸易顺差的方式让欧洲实体经济中的资本流向德国，同时德国又可以在国际资本市场大规模、低成本地吸纳金融资本，然后德国再以资本输出的方式将巨额资金“二次分配”到其他欧盟国家，以资本输出的方式对欧盟其他成员国进行直接投资和证券投资。^[由此可以推论：德国有巨额经常账户顺差和资本账户逆差。] 在欧洲的这种资本循环中，**德国始终掌控着欧洲资本流动的规模和流向，实际上扮演着“欧洲银行家”的角色**。

### 德国的成功来源于欧元

欧元 -> 贸易顺差：  德国贸易顺差的一半以上都来自欧盟内部，并且这一份额在欧元引入之后一直增长迅速。

欧元 -> 财政能力：强劲的出口让德国经济赢得了国际资本市场的信任和青睐，德国国债受到追捧，收益率下降。特别是 2009 年欧债危机爆发后，德国成为了资本的避风港，进一步拉低了德国的利率水平，德国的融资能力在危机中被大大增强了，德国 10 年期国债利率在欧债危机期间长期都处于 2% 以下，如果扣除通货膨胀的因素，相当于德国基本可以“免费”从全球借钱。

欧元 -> 企业竞争力：国家层面的这种融资能力体现在经济微观层面就是企业对资本的掌控力，德国的企业的融资能力远超其他成员国企业，比如在欧债危机期间，一笔 5 年期以内的 100 万欧元的贷款，西班牙企业需要支付 6.5% 的利息，意大利企业是 6.24%，而德国企业仅需 4.04%。德国企业的融资成本更低，这让其他欧盟成员国企业在市场竞争中明显地处于不利境地。


