---
title: "《未来世界的幸存者》读书笔记"
author: "黄蒙"
date: '2019-10-25'
categories: 经济
tags: 人工智能
slug: 人工智能普及的恐怖未来-未来世界的幸存者-读书笔记
---

<strong><font color = 'darkblue'>有了汽车，骡马几乎彻底消失，马车夫全部再就业；机械普及，女性的就业机会空前增加，性别平等取得突破性进展。科技的重大进步，对经济结构乃止社会结构总会产生深远的影响。而这一次的智能革命，甚至有可能颠覆我们熟知的全部社会架构。</font></strong>

### 1 技术迭代与中年失业

技术迭代越来越快，但“终身学习”对于绝大多数人都是不现实的。人到中年，精力衰退，上有老下有小。只有高收入阶层凭借积蓄可以整装再出发，大多数人则根本没有条件对一个新领域重头学起。

### 2 教育不足与无用人口

人类社会出现一个庞大的、无用的无产阶级，他们对“国家”不再有用，国家便很有可能会忽略他们的需求。只把他们圈养起来，**甚至实施绝育**。

大学起源于修道院，其知识传授模式越来越难以适应当今的社会需求。一是脱离一线生产实际；二是极其耽误学生的时间。它目前更多的作用在社会层面而非教育层面。大学的本意是培养学术人才，多数人其实应该选择职业教育，快速进入接触和学习一线岗位所需的知识。

### 3 养老金缺口

人类会渐渐支持安乐死，因为很可能钱用光了，人还没死。日本已经出现了这么一批老年赤贫阶层。

### 4 人生的 B 计划

B 计划绝不是浪漫的，而是用来救命的。

### 5 超级人类

#### 5.1 基因编辑

有钱人通过基因编辑，使自己的后代更聪明、更健康、更漂亮，社会分层会因此彻底固化。

#### 5.2 器官移植或人造器官

取代衰竭的器官，延长寿命或增强功能。

器官移植和换头术一旦成熟，在完成生育或器官衰老后，只要保住脑袋就可以了，其他部分都可以换，人类的寿命和肉体功能都将大幅增加。到时候，人与机械融为一体：机械给了人更长的寿命，人给了机械灵魂。

### 6 技术复杂化

没有人能够理解全部技术，进而预测某个领域的技术发展会引起整个系统怎样的变化。——所以，玄学思维模式要回归了吗？

技术的危机只能用更好的技术解决，否则人类社会就有立刻崩溃的危险。

### 7 人类历史的三种周期

短期看政治；中期看经济；长期看技术

### 8 卡辛斯基的警告论文

**Title**: Industrial Society and Its Future

**Author**: Ted Kaczynski

观点：智能机械将使得大量普通人被贬低到家畜或宠物的地位。

<br>
<br>

### <font color = 'red'>感想：从个人到国家，我们所做的一切努力，都只是为了最大化自己和后代生存的概率。</font>